name: 七星拳

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 */9 * *'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pip install requirements.txt

    - name: 开始爬取
      env:
        IBM_APP_NAME: "IBM sheet"
      run: |
        python run qxv.py
